# Set custom properties and
# rename this file to docker-compose.yml
# or use docker-compose -f option
lvkserver:
  build: .
  volumes:
    - ./flvs:/flvs
  ports:
    - "888:80"
    - "1937:1935"
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"