lvkserver:
  build: ./nginx
  volumes:
    - ./flvs:/flvs
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
    - node
  restart: always

node:
  build: ./nodejs
  restart: always
